apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: yurt-tunnel-agent
  name: yurt-tunnel-agent
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: yurt-tunnel-agent
  template:
    metadata:
      labels:
        k8s-app: yurt-tunnel-agent
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/os: linux
      volumes:
      - name: serviceaccount
        configMap:
          name: yurt-tunnel-agent-sa
      containers:
      - command:
        - yurt-tunnel-agent
        args:
        - --cluster-name=cls-t8gz6mgd.kube-system.svc
        - --apiserver-addr=1.1.1.1:31501
        - --tunnelserver-addr=1.1.1.1:31502
        - --v=4
        image: huxl/yurt-tunnel-agent:latest-amd64
        imagePullPolicy: Always
        name: yurt-tunnel-agent
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /var/lib/yurttunnel-agent/serviceaccount
          name: serviceaccount
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yurt-tunnel-agent-sa
  namespace: kube-system
data:
  token: |-
    TODO
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    TODO
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Service
metadata:
   name: cls-t8gz6mgd
   namespace: kube-system
spec:
  selector:
    component: kube-apiserver
  ports:
  - port: 6443
    targetPort: 6443
