apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: yurt-tunnel-agent
  name: yurt-tunnel-agent
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: yurt-tunnel-agent
  template:
    metadata:
      labels:
        k8s-app: yurt-tunnel-agent
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/os: linux
      volumes:
      - name: serviceaccount
        configMap:
          name: yurt-tunnel-agent-sa
      containers:
      - command:
        - yurt-tunnel-agent
        args:
        - --cluster-name=cls-t8gz6mgd.kube-system.svc
        - --apiserver-addr=132.232.31.102:31501
        - --tunnelserver-addr=132.232.31.102:31502
        - --v=4
        image: huxl/yurt-tunnel-agent:v0.3.0-amd64
        imagePullPolicy: Always
        name: yurt-tunnel-agent
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /var/lib/yurttunnel-agent/serviceaccount
          name: serviceaccount
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yurt-tunnel-agent-sa
  namespace: kube-system
data:
  token: |-
    eyJhbGciOiJSUzI1NiIsImtpZCI6ImNRTlNreUsxUWNWYnp5OHVTelVQUlM2QXUzc19zS2RhS2ZxVGRtakVIX00ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrOHNhZG1pbi10b2tlbi1wam02dyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrOHNhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjNiOWIzOTAzLTk0OTEtNDU2NC1iYzUwLWQ0OGRjOTkzOTE1NyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTprOHNhZG1pbiJ9.C0VwNFy_xwklkIGGKOa1bINmlK0kfLH7B_7ShcRo8kjT-rny2hJDYYCs4VkSwG903gOApAZnBlF9hmPj5f18SiowfV6VXktBpULghKAy0auIQknhAWuJdrssL2al7RsapeJTIFpQp53Qej-6cL0dBaBlbzwE7tpH7oUmWcXqfe0w8nQFFZ_3d2vl-Yuz1Z0Xp_6h7AltDM5G0ZUCE82KFZBFvtmQ36NLQKYNEmpd2rJgQQtS4BTvySX9Gth8fq7BYn-EdgPYezi9eGKpzQPe2iemgdh0N13V6LVmWRdEfKZSeuzrEiFWvojVeHvQ8CsDr9wHhbhT7Af1Ct9JRLJVVA
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIC5zCCAc+gAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
    cm5ldGVzMB4XDTIxMDIyNDE0NDYwNloXDTMxMDIyMjE0NDYwNlowFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMjq
    o0GD3enILRLOtkMDqISc+NHnCPa7g1wo40Zfr681UDYXiVD1i51fYDmVcPm3Z4tb
    wY5IrdTXcnDUWqJSXAa/5LG0BM/abXTNU/Aq47b5Gto4U6SlYy/pCZ2V8eQ38Wd1
    +rd6KTpZ8BqiM5hqkN9kKInlJTh41U1kwgiJb2+NuroBL9kCfZ0CGd/On+5NIyXf
    qbePh11DD0C8Bw5uoOWkxhZ5k0ypqk2zElS5XevIXle1TxWLLv6D+oLuB9sIjjQ8
    rdwLOUFRpHtqoX1lfPbYyKBg4a8OiY3tZBQoe9JLwetPg9TzPNnStgvtrwSlxnJ2
    +6bP93Vv5IBGFH8xpLUCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
    /wQFMAMBAf8wHQYDVR0OBBYEFKu43oVbxzPtATtdZ+1xhKwGo22jMA0GCSqGSIb3
    DQEBCwUAA4IBAQBUD0uh7xn4n8Z6DUPAEqDtiDBBYIAsJ69E1N8sK3m/CjqZYcut
    gLWDHzyikw3GqUEAJpVkb0DbYGW14xhbbf64KXFwTFzxAmIPe791mAS1Dd3Gsvfi
    RRptbQmRkDG78ZQkZGAAGfS3cWLO5cshjHKjY0utwEsD5Ntd/mDV3l5Ghmsz1hyW
    NeOAhUgoIX5cYdf1/UrAsSTW+vgj6E5G5oQFdDLSKNg9knuRnijN9QJ+90Vxb/wG
    52wfN3S9e3OCjwg7odQIACN0gAR0sol6M3T0iH4RR0hg83zl9t1wQc0cH5gba2rV
    tEttk2kcoMabNLolKT/XvzqEermfe7HTCgdS
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Service
metadata:
   name: cls-t8gz6mgd
   namespace: kube-system
spec:
  selector:
    component: kube-apiserver
  ports:
  - port: 6443
    targetPort: 6443
