apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: yurt-tunnel-server
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
  - patch
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  resourceNames:
  - "kubernetes.io/legacy-unknown"
  verbs:
  - approve
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yurt-tunnel-server
subjects:
  - kind: ServiceAccount
    name: yurt-tunnel-server
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: yurt-tunnel-server
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yurt-tunnel-server
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: x-tunnel-server-svc
  namespace: kube-system
  labels:
    name: yurt-tunnel-server
spec:
  type: NodePort 
  ports:
  - port: 10261
    targetPort: 10261
    name: reverseproxy
    nodePort: 31501
  - port: 10262
    targetPort: 10262
    name: tcp
    nodePort: 31502
  - port: 10263
    targetPort: 10263
    nodePort: 31503
    name: https
  selector:
    k8s-app: yurt-tunnel-server
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yurt-tunnel-server
  namespace: kube-system
  labels:
    k8s-app: yurt-tunnel-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: yurt-tunnel-server
  template:
    metadata:
      labels:
        k8s-app: yurt-tunnel-server
    spec:
      serviceAccountName: yurt-tunnel-server
      restartPolicy: Always
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/os: linux
      containers:
      - name: yurt-tunnel-server
        image: huxl/yurt-tunnel-server:latest-amd64
        imagePullPolicy: Always
        command:
        - yurt-tunnel-server
        args:
        - --bind-address=0.0.0.0
        - --cert-ips=132.232.31.102,139.155.48.141,139.155.57.224
        - --proxy-strategy=destHost
        - --v=4
